# Generated by Django 5.0.6 on 2024-06-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='brojOdrzaniNastani',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band',
            name='godinaFormiranje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band',
            name='imeDrzava',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='daliENaOtvoreno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='vremeOdrzuvanje',
            field=models.DateField(blank=True, null=True),
        ),
    ]
