# Generated by Django 5.0.6 on 2024-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50)),
                ('imeProizveduvac', models.CharField(max_length=50)),
                ('maxPatnici', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('godinaRagjanje', models.CharField(max_length=50)),
                ('vkuspnoCasoviLetano', models.IntegerField()),
                ('cinVoKompanija', models.CharField(max_length=50)),
            ],
        ),
    ]
