# Generated by Django 5.0.6 on 2024-05-20 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLyBaloonApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviokompanija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('godinaOsnovanje', models.CharField(max_length=50)),
                ('letaNadvorOdEvropa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AviokompanijaPilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviokompanija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FLyBaloonApp.aviokompanija')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FLyBaloonApp.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Let',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.CharField(max_length=50)),
                ('aerodromSletuva', models.CharField(max_length=50)),
                ('aerodromPoletuva', models.CharField(max_length=50)),
                ('fotografija', models.ImageField(blank=True, null=True, upload_to='flights/')),
                ('aviokompanija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FLyBaloonApp.aviokompanija')),
                ('balon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FLyBaloonApp.ballon')),
                ('kreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FLyBaloonApp.pilot')),
            ],
        ),
    ]
